# Generated by Django 4.2.5 on 2023-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproject',
            name='saved_proj_id',
            field=models.IntegerField(),
        ),
    ]
